[gravity]
domain = "gravity"
host = "0.0.0.0"
port = 4222
pingInterval = 10
maxPingsOutstanding = 3
maxReconnects = -1

[adapter]
adapterID = "rest_adapter"
adapterName = "REST Adapter"

# Authentication
appID = "anonymous"
accessKey = ""

[service]
port = 8080

[source]
config = "./settings/sources.json"
