[gravity]
domain = "gravity"
host = "0.0.0.0"
port = 4222
pingInterval = 10
maxPingsOutstanding = 3
maxReconnects = -1

[adapter]
adapter_id = "rest_adapter"
adapter_name = "REST Adapter"

[service]
port = 8080

[source]
config = "./settings/sources.json"
